{% set version = "0.2.0" %}

package:
  name: r-dbmodelr
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/LainPavot/DBModelR/archive/v{{ version }}.zip
  md5: 8268c1d038d03e5429cd50d339c3de13
  sha256: 3a3269aa6e1e244f364e98b1280228533bd09b75b18ee3ed69b8b2f970e91457

build:
  noarch: generic
  merge_build_host: true
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  script: R CMD INSTALL --build .

requirements:
  host:
    - sqlite
    - r-base
    - r-rlang
    - r-purrr
    - r-blob
    - r-dbi
    - r-rsqlite
  run:
    - sqlite
    - r-base
    - r-rlang
    - r-purrr
    - r-blob
    - r-dbi
    - r-rsqlite

test:
  commands:
    - R -e "library('DBModelR')"

about:
  home: https://github.com/LainPavot/DBModelR
  license: AGPL-3.0-or-later
  license_file: LICENSE
  summary: 'An ORM in R'
  description: |
    An ORM to handle database request through R objects.
  dev_url: https://github.com/LainPavot/DBModelR
  doc_url: https://github.com/LainPavot/DBModelR
  doc_source_url: https://github.com/LainPavot/DBModelR/blob/v{{ version }}/README.md

extra:
  recipe-maintainers:
    - LainPavot
    - conda-forge/r
